# Generated by Django 4.2.30 on 2026-05-13 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hortas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='loja/')),
                ('preco_moedas', models.PositiveIntegerField()),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('horta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_loja', to='hortas.horta')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('total_moedas', models.PositiveIntegerField()),
                ('realizada_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='loja.itemloja')),
            ],
        ),
    ]
