# Generated by Django 4.2.30 on 2026-05-13 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Missao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('nivel_minimo', models.PositiveIntegerField(default=1)),
                ('recompensa_moedas', models.PositiveIntegerField(default=0)),
                ('recompensa_xp', models.PositiveIntegerField(default=0)),
                ('prazo', models.DateTimeField(blank=True, null=True)),
                ('vagas', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('encerrada', 'Encerrada')], default='aberta', max_length=20)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacaoMissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('aceita', 'Aceita'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='aceita', max_length=20)),
                ('foto_comprovante', models.ImageField(blank=True, null=True, upload_to='comprovantes/')),
                ('aceita_em', models.DateTimeField(auto_now_add=True)),
                ('concluida_em', models.DateTimeField(blank=True, null=True)),
                ('missao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='missoes.missao')),
            ],
        ),
    ]
