# Generated by Django 4.2.30 on 2026-05-13 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hortas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participacaomissao',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='missao',
            name='horta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missoes', to='hortas.horta'),
        ),
        migrations.AlterUniqueTogether(
            name='participacaomissao',
            unique_together={('usuario', 'missao')},
        ),
    ]
