# Generated by Django 4.2.30 on 2026-05-13 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.ImageField(blank=True, null=True, upload_to='conquistas/')),
                ('tipo', models.CharField(choices=[('missoes', 'Missões Concluídas'), ('nivel', 'Nível Atingido'), ('moedas', 'Moedas Acumuladas')], max_length=20)),
                ('valor_necessario', models.PositiveIntegerField(help_text='Ex: 10 missões, nível 5, 500 moedas')),
            ],
        ),
        migrations.CreateModel(
            name='ConquistaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desbloqueada_em', models.DateTimeField(auto_now_add=True)),
                ('conquista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='conquistas.conquista')),
            ],
        ),
    ]
