# Generated by Django 4.2.30 on 2026-05-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransacaoMoeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('descricao', models.CharField(max_length=255)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
