# Generated by Django 4.2.30 on 2026-05-13 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hortas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horta',
            name='gestor',
            field=models.ForeignKey(limit_choices_to={'tipo': 'gestor'}, on_delete=django.db.models.deletion.PROTECT, related_name='hortas', to=settings.AUTH_USER_MODEL),
        ),
    ]
